### ISSUE TITLE
你好，希望应聘贵公司的前端工程师实习工作

### ISSUE THREAD

**Issue by ghost** [liangxiaojie/liangxiaojie.github.io#1]
你好，看到您是聚道科技的前端工程师，我想申请贵公司的前端工程师实习的工作，把个人简历发送到您的邮箱(liangxiaojie@genedock.com)里了，希望您可以查收一下，谢谢  :)

**Comment by liangxiaojie** [comment]
@guihailiuli 嗯，好的，收到，我发给我们团队看一下^_^

**Comment by ghost** [comment]
@liangxiaojie 恩恩，谢谢喔
